# Generated by Django 5.0.6 on 2024-05-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Relogio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
                ("cor", models.CharField(max_length=10)),
                ("marca", models.CharField(max_length=30)),
                ("imagem", models.ImageField(upload_to="")),
                ("genero", models.CharField(max_length=1)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("material", models.CharField(max_length=20)),
                ("peso", models.CharField(max_length=20)),
            ],
        ),
    ]
