# Generated by Django 5.0.6 on 2024-06-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Relogios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relogio",
            name="imagem",
            field=models.ImageField(upload_to="Relogios_fotos"),
        ),
    ]
