# Generated by Django 5.0.6 on 2024-06-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relogios', '0002_alter_relogio_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relogio',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='relogio',
            name='material',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='relogio',
            name='peso',
            field=models.FloatField(blank=True, choices=[('1', '1'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('19.2', '19.2'), ('20', '20'), ('22', '22'), ('24', '24')], max_length=4, null=True),
        ),
    ]
