# Generated by Django 5.0.6 on 2024-06-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relogios', '0003_alter_relogio_genero_alter_relogio_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relogio',
            name='quantidadeDisponivel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
