# Generated by Django 5.0.6 on 2024-06-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relogios', '0004_relogio_quantidadedisponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relogio',
            name='quantidadeDisponivel',
            field=models.IntegerField(),
        ),
    ]
