# Generated by Django 5.0.6 on 2024-06-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relogios', '0005_alter_relogio_quantidadedisponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relogio',
            name='imagem',
            field=models.ImageField(upload_to='Relogios/fotos'),
        ),
        migrations.AlterField(
            model_name='relogio',
            name='peso',
            field=models.FloatField(choices=[(1.0, '1'), (10.0, '10'), (12.0, '12'), (14.0, '14'), (16.0, '16'), (18.0, '18'), (19.2, '19.20'), (20.0, '20'), (22.0, '22'), (24.0, '24')]),
        ),
    ]
