# Generated by Django 5.0.6 on 2024-06-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relogios', '0006_alter_relogio_imagem_alter_relogio_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relogio',
            name='imagem',
            field=models.ImageField(height_field=300, upload_to='Relogios/fotos', width_field=300),
        ),
    ]
