# Generated by Django 5.0.6 on 2024-06-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relogios', '0007_alter_relogio_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relogio',
            name='imagem',
            field=models.ImageField(upload_to='Relogios/fotos'),
        ),
    ]
