# Generated by Django 5.0.6 on 2024-06-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relogios', '0008_alter_relogio_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relogio',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=9),
        ),
        migrations.AlterField(
            model_name='relogio',
            name='imagem',
            field=models.ImageField(height_field='300', upload_to='Relogios/fotos', width_field='300'),
        ),
        migrations.AlterField(
            model_name='relogio',
            name='peso',
            field=models.SmallIntegerField(choices=[(1, '1 kilate'), (10, '10 kilates'), (12, '12 kilates'), (14, '14 kilates'), (16, '16 kilates'), (18, '18 kilates'), (20, '20 kilates'), (22, '22 kilates'), (24, '24 kilates')]),
        ),
    ]
