# Generated by Django 5.0.6 on 2024-06-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relogios', '0009_alter_relogio_genero_alter_relogio_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relogio',
            name='imagem',
            field=models.ImageField(upload_to='Relogios/fotos'),
        ),
    ]
