# Generated by Django 5.0.6 on 2024-06-28 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relogios', '0010_alter_relogio_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relogio',
            options={'verbose_name': 'Relógio', 'verbose_name_plural': 'Relógios'},
        ),
    ]
