# Generated by Django 5.0.6 on 2024-06-23 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Relogios', '0005_alter_relogio_quantidadedisponivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('relogio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relogios.relogio')),
            ],
        ),
    ]
