# Generated by Django 5.0.6 on 2024-06-27 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrinho', '0001_initial'),
        ('Relogios', '0010_alter_relogio_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='relogio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to='Relogios.relogio'),
        ),
    ]
