# Generated by Django 5.0.6 on 2024-06-28 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrinho', '0004_alter_carrinho_usuario'),
        ('Relogios', '0011_alter_relogio_options'),
        ('Usuarios', '0023_alter_usuario_options_remove_usuario_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='relogio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relogios.relogio'),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to='Usuarios.usuario'),
        ),
    ]
