# Generated by Django 5.0.6 on 2024-06-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="permissao",
            field=models.BooleanField(default=False),
        ),
    ]
