# Generated by Django 5.0.6 on 2024-06-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0002_alter_user_permissao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dataNascimento",
            field=models.DateField(verbose_name="Data de Nascimento"),
        ),
    ]
