# Generated by Django 5.0.6 on 2024-06-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0003_alter_user_datanascimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dataNascimento",
            field=models.DateField(),
        ),
    ]
