# Generated by Django 5.0.6 on 2024-06-17 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relogios', '0003_alter_relogio_genero_alter_relogio_material_and_more'),
        ('Usuarios', '0009_alter_usuario_email_alter_usuario_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('relogio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relogios.relogio')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='carrinho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.carrinho'),
        ),
    ]
