# Generated by Django 5.0.6 on 2024-06-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0010_carrinho_usuario_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(error_messages={'unique': 'O nome é um campo unico'}, max_length=50),
        ),
    ]
