# Generated by Django 5.0.6 on 2024-06-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0011_alter_usuario_email_alter_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(error_messages={'unique': 'O nome é um campo unico'}, max_length=50, unique=True),
        ),
    ]
