# Generated by Django 5.0.6 on 2024-06-18 01:36

import Usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0012_alter_usuario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dataNascimento',
            field=models.DateField(blank=True, null=True, validators=[Usuarios.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[Usuarios.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=50, validators=[Usuarios.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(max_length=50, validators=[Usuarios.validators.validate_name]),
        ),
    ]
