# Generated by Django 5.0.6 on 2024-06-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0014_alter_usuario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sobrenome',
        ),
    ]
