# Generated by Django 5.0.6 on 2024-06-18 19:42

import Usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0015_remove_usuario_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=14, null=True, validators=[Usuarios.validators.validate_cpf]),
        ),
    ]
