# Generated by Django 5.0.6 on 2024-06-18 19:44

import Usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0016_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[Usuarios.validators.validate_cpf]),
        ),
    ]
