# Generated by Django 5.0.6 on 2024-06-19 01:32

import Usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0017_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Já existe um usuário com esse email, tente novamente'}, max_length=254, unique=True, validators=[Usuarios.validators.validate_email]),
        ),
    ]
