# Generated by Django 5.0.6 on 2024-06-19 02:06

import Usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0018_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'Já existe um usuário com esse cpf'}, max_length=14, unique=True, validators=[Usuarios.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Já existe um usuário com esse email'}, max_length=254, unique=True, validators=[Usuarios.validators.validate_email]),
        ),
    ]
