# Generated by Django 5.0.6 on 2024-06-20 20:06

import Usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0020_alter_usuario_cpf_alter_usuario_datanascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'Já existe um usuário com esse cpf'}, max_length=14, unique=True, validators=[Usuarios.validators.validate_cpf]),
        ),
    ]
