# Generated by Django 5.0.6 on 2024-06-28 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0022_alter_usuario_carrinho_delete_carrinho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='carrinho',
        ),
    ]
